# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Format

on:
  push:
    branches: [ "42-layout-based-on-cells-instead-of-rows" ]
  pull_request:
    branches: [ "42-layout-based-on-cells-instead-of-rows" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3        
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      
      - run: flutter --version  
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
